### ISSUE TITLE
Default objectType is serialized

### ISSUE THREAD

**Issue by Selindek** [BerryCloud/xapi-java#196] opened 2023-07-27 13:31 UTC
### Summary

The Activity objectType property is present when serialising an Activity even though the objectType is optional and not required when the objectType value is Activity. This also applies to actor or authority when it is of type agent.

### Steps to reproduce

```java

final var json = """
    {
        "actor":{
            "name":"A N Other",
            "mbox":"mailto:another@example.com"
        },
        "verb":{
            "id":"http://adlnet.gov/expapi/verbs/attempted"
        },
        "object":{
            "id":"https://example.com/activity/simplestatement"
        }
    }""";

final var statement = objectMapper.readValue(json, Statement.class);

// When Deserializing Statement With Activity
final var result = objectMapper.writeValueAsString(statement);

// Then ObjectType Is Present 
assertThat(result, hasNoJsonPath("$.object.objectType"));

```

### Expected behaviour

ObjectType is not present in deserialized Statement

### Actual behaviour

ObjectType is present in serialized Statement

**Comment by thomasturrell** [comment] 2023-08-07 10:11
@Selindek tells me that the model in xAPI-Java is opinionated and always added the ObjectType, which is permitted by the xAPI specification. 

There is a related a bug in the LRS conformance suite. An issue has been raised at https://github.com/adlnet/lrs-conformance-test-suite/issues/259.

Closing this issue since this is not a bug with the xAPI-Java model.

**Closed by thomasturrell** 2023-08-07 10:11 UTC
Labels: bug
